logs:
  configs:
  - name: default
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    # - job_name: system
    #   static_configs:
    #   - targets:
    #       - localhost
    #     labels:
    #       job: varlogs
    #       server: SERVER_LABEL_HOSTNAME
    #       __path__: /var/log/*log

    - job_name: containers
      static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          server: SERVER_LABEL_HOSTNAME
          __path__: /var/lib/docker/containers/*/*log

      pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:

      - json:
          expressions:
            tag:
          source: attrs

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: tag

      - regex:
          expression: (?P<container_name>(?:^[^.]*))
          source: container_name

      - timestamp:
          format: RFC3339Nano
          source: time

      - labels:
          stream:
          container_name:

      - labeldrop:
        - filename

      - output:
          source: output
    
    clients:

