metrics:
  configs:
    - name: default
      scrape_configs:
        - job_name: grafana-agent
          static_configs:
            - targets: 
              - 'localhost:12345'
              labels:
                instance: 'grafana-agent'


