version: "3.9"

x-logging: &logging
  logging:
    driver: 'json-file'
    options: 
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

volumes:
  grafana-agent_data: {}
  prometheus_data: {}
  loki_data: {}
  grafana_data: {}

services:
  prometheus:
    <<: *logging
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus-config.yml:/etc/prometheus/config.yml
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--enable-feature=remote-write-receiver'

  loki:
    <<: *logging
    image: grafana/loki:latest
    volumes:
      - loki_data:/tmp
      - ./loki-config.yml:/etc/loki/config.yml
    command:
      - '--config.file=/etc/loki/config.yml'

  grafana:
    <<: *logging
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000

  grafana-agent:
    <<: *logging
    image: grafana/agent:latest
    user: root
    volumes:
      - grafana-agent_data:/etc/agent/data

      - ./grafana-agent/entrypoint.sh:/configs/entrypoint.sh
      - ./grafana-agent/prometheus-custom.yml:/configs/prometheus-custom.yml
      - ./grafana-agent/promtail-lokiurl.yml:/configs/promtail-lokiurl.yml
      - ./grafana-agent/file_sd:/etc/prometheus/file_sd

      - ./grafana-agent/global.yml:/configs/global.yml
      - ./grafana-agent/intergrations.yml:/configs/intergrations.yml
      - ./grafana-agent/prometheus.yml:/configs/prometheus.yml
      - ./grafana-agent/promtail.yml:/configs/promtail.yml
      - ./grafana-agent/traces.yml:/configs/traces.yml

      - /etc/machine-id:/etc/machine-id:ro

      - /var/log:/var/log:ro
      - ${DOCKER_CONTAINER_LOGS_PATH:-/var/lib/docker/containers}:/var/lib/docker/containers:ro

      - /:/host/root:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    entrypoint: ./configs/entrypoint.sh
    command: ["/bin/grafana-agent"]
    environment:
      SERVER_LABEL_HOSTNAME: ${SERVER_LABEL_HOSTNAME:-notset}
